### ISSUE TITLE
DFP-34X-2C2 - SN no state 05

### ISSUE THREAD

**Issue by thiagoasilva89** [Anime4000/RTL960x#108]
Hello, I am not able to place the RN according to the image in the HGU.

![image](https://user-images.githubusercontent.com/33902490/207992848-da793cc5-e08e-429b-b3d5-628762a618f8.png)

I'm using FW V1.7.1-220916

![image](https://user-images.githubusercontent.com/33902490/207993032-9c48ee0a-8c81-449a-b02a-a27535c82d87.png)

By telnet is also not possible.

Thanks.

**Comment by Anime4000** [comment]
first, SN must be 4 ASCII + 8 HEX
so,
your 16 hex long SN must convert the first 8 HEX into ASCII

please re-read the flash get set readme
