### ISSUE TITLE
Change IP address via telnet

### ISSUE THREAD

**Issue by Pukkahq** [Anime4000/RTL960x#111]
I have changed the IP address via telnet # ifconfig br0 192.168.15.1 netmask 255.255.255.0 broadcast 192.168.15.255

I can no longer login via telnet but I can Ping the device ok. What else needs changing?

**Comment by Anime4000** [comment]
that need restart telnet daemon as it bind to IP, you should use `flash set LAN_IP_ADDR` and `flash set LAN_SUBNET`
then reboot

**Comment by Pukkahq** [comment]
That worked great :) the full command was **flash set LAN_IP_ADDR 192.168.254.1** **flash set LAN_SUBNET 255.255.255.0**
