### ISSUE TITLE
DFP-34X-2C2 disappeared after changing LAN_SDS_MODE

### ISSUE THREAD

**Issue by Voidstranger** [Anime4000/RTL960x#169]
Hi. I changed LAN_SDS_MODE to 4 and can't reach sfp-module anymore.
I use BPI-R3 router with OpenWRT and other user confirmed, that he is using DFP-34X-2C2 with BPI-R3 router too and he hasn't any problems with 4, 5, 6 option of LAN_SDS_MODE. I'm using M110_sfp_ODI_210702 firmware.

ethtool eth1 (eth1 is port, where sfp-module is located) output:
![Screenshot 2023-06-27 203419](https://github.com/Anime4000/RTL960x/assets/46969906/faa0ded2-1535-4ed0-a23f-e2676c0d2897)
It seems, that there is link on the interface.

No Rx to eth1. Why?
![Screenshot 2023-06-27 222617](https://github.com/Anime4000/RTL960x/assets/46969906/b87c47f4-3f09-482b-ba2f-01c2f0304722)

Also I changed sfp's ip address to 192.168.2.1. But this isn't a problem, right?

**Comment by Anime4000** [comment]
the ODI Stick have auto negotiate which LAN Mode to use, perhaps your OpenWRT need the tweak first.

try revert back to 1G on OpenWRT if your new SFP are working...

if working, then try adjusting the OpenWRT router,

if is not, you need reset it back via TTL UART

**Comment by Voidstranger** [comment]
Also, my stick is in epon mode. Can this cause an issue?

As for  UART.
I can see two little Rx and Tx spots near the chip on the stick. Ground is ground, I can connect it to metal cage, for example, right? But do I need to connect 3.3 cable? Where should I connect it?

**Comment by Anime4000** [comment]
you can use `flying probe` if don't want do soldering, this much cleaner.
![image](https://github.com/Anime4000/RTL960x/assets/1908715/db58e095-a83a-4d5f-a023-024f055c751d)

I suggest you do a factory reset, and try not change default IP Address, leave it as 192.168.1.1/24, this known issue most of the RTL based stick if not configured properly
