### ISSUE TITLE
How to enable the 4-port emulation feature on HSGQ DFP-34X-2C2

### ISSUE THREAD

**Issue by zongmingye** [Anime4000/RTL960x#225]
![Xnip2023-12-17_18-15-23](https://github.com/Anime4000/RTL960x/assets/46990288/498d7965-08f4-4c32-8c85-533917e323d0)
![Xnip2023-12-17_18-21-39](https://github.com/Anime4000/RTL960x/assets/46990288/08a141e8-aa70-4a20-8ccc-3b24a4edded0)
I have two pppoe accounts that use the same onu’s loid. I would like to know how to set up simultaneous PPPoE dialing on ROS. Can enabling the 4-port emulation to dial at the same time? currently, only one account can successfully dial at a time using the same port

**Comment by Anime4000** [comment]
both are come same VLAN ? or not using VLAN?

**Comment by zongmingye** [comment]
Both used same vlan id 41
![IMG_7076](https://github.com/Anime4000/RTL960x/assets/46990288/f90b5b29-5fae-488a-98d4-01aa5326b2bc)

**Comment by Anime4000** [comment]
I think better make it transparent bridge and add VLAN at Mikrotik instead.
This what do with my internet:
![image](https://github.com/Anime4000/RTL960x/assets/1908715/352dd3ca-d3db-4c22-96e4-dd7d5e4fea0f)

**Comment by zongmingye** [comment]
In the end,the problem was fixed by useing vrrp interface
![2023-12-19_091828](https://github.com/Anime4000/RTL960x/assets/46990288/ba821cd6-e0ad-4cba-9191-d9760eabf8bd)

**Comment by Anime4000** [comment]
wow, your ISP need VRRP to work?
we here just use same VLAN with many PPPoE Client

can you show this page?
![image](https://github.com/Anime4000/RTL960x/assets/1908715/1907e106-ccbe-44e0-8aaf-c416c4d31209)
