### ISSUE TITLE
Debug firmware for TP-Link BE900 to enable SFP 2.5G speeds?

### ISSUE THREAD

**Issue by d5aqoep** [Anime4000/RTL960x#228]
I saw firmware for BE800 but any such debug firmware exists for BE900 model or ways to obtain it?

**Comment by Anime4000** [comment]
that firmware from ISP Employee who buy BE800 and email TP-Link Support.

maybe you can send email to TP-Link about BE900, and tell them BE800 debug firmware allow 2.5G PON Stick to work, they might help you because of this premium router 😄
