### ISSUE TITLE
dfp-34x-2c2 can't see ISP gateway

### ISSUE THREAD

**Issue by Smotrov** [Anime4000/RTL960x#230]
Bought dfp-34x-2c2 instead of bricked V2801F (which worked for a while)
ISP white listed MAC of dfp-34x-2c2.  My ISP is EPON with static IP.

It supposed to replace ISPs  PON 
![IMG_2994](https://github.com/Anime4000/RTL960x/assets/7815789/95b8d436-6fde-4ba4-9637-4d8e6abc3d0e)

Link Is OK and I can see some packets. 

<img width="694" alt="Знімок екрана 2023-12-22 о 20 46 19" src="https://github.com/Anime4000/RTL960x/assets/7815789/406067e0-24b2-429b-8c89-5661386739f8">
<img width="691" alt="Знімок екрана 2023-12-22 о 20 46 27" src="https://github.com/Anime4000/RTL960x/assets/7815789/e341cddf-5347-4b76-af5a-fb5f8af59cbd">

<img width="455" alt="image" src="https://github.com/Anime4000/RTL960x/assets/7815789/0820f4fb-8cd1-40b7-b195-7a483e774049">

However, I just can't ping ISP gateway even from my Mikrotik RB5009 router directly. All timed out.
Any ideas would be highly appreciated. 

PS: On the same router with the same setup V2801F was working out-of-the-box without any additional settings.

**Comment by Smotrov** [comment]
Besides, it is interesting which settings are essential for EPON ISP (apart from MAC address). Everybody talking about GPON mostly...

**Comment by Anime4000** [comment]
> Besides, it is interesting which settings are essential for EPON ISP (apart from MAC address). Everybody talking about GPON mostly...

Sadly yes, almost everyone use GPON including me 😅

So, documentation about EPON is very limited here, perhaps you can try and find out

if you have Discord, join this chat forum (7 days limit start from today):
https://discord.gg/WQQEUvFM

**Comment by korzhyk** [comment]
@Smotrov what ISP do you use?

**Comment by Smotrov** [comment]
I'm on Triolan Ukraine. Now everything works perfectly fine. The only thing was to properly set VLAN. Either on SFP module or on the Interface on the router. 

I find VLAN ID I just did "touch" on SFP interface and from there VLAN ID become obvious :-)
