### ISSUE TITLE
TP-Link BE900 Debug firmware to enable 2.5G SFP port (Link inside)

### ISSUE THREAD

**Issue by d5aqoep** [Anime4000/RTL960x#235]
![Screenshot 2024-01-04 155704](https://github.com/Anime4000/RTL960x/assets/28061422/f62f5083-d5df-420b-9377-5e6082434ff5)

https://www.mediafire.com/file/8x1gbe6tped9mjs/BE900v1_1.1.3_240104_SFP_beta.zip/file

After updating to above debug beta firmware do the following (pass the debug commands in the web page given)

Go to http://192.168.0.1/webpages/debug.html

combo_debug stop
combo_debug set plus
combo_debug ipg_set combo10g 1_192bit

I report that both ODI DFP-34X-2C2 and Lu Leey 2.5G GPON sticks work correctly at 2.5Gbps Full Duplex speeds in my BE900
@Anime4000

**Comment by Anime4000** [comment]
Nice, I add the firmware into repo, and link to this!

Good thing TP-Link listen to their customer, unlike Ubiquiti, Aruba and Fortinet (need CRS305 to make it 10G, cannot plug directly to save space)

**Comment by Anime4000** [comment]
this is your post?
![Screenshot_20240104_203752_Firefox.jpg](https://github.com/Anime4000/RTL960x/assets/1908715/4d9ffd7f-1430-4eff-a0e1-e67ee19477c5)

**Comment by d5aqoep** [comment]
No. Guess they gave out the firmware today to whoever asked.

**Comment by Anime4000** [comment]
I mark this issue as complete, TP-Link working to make GPON Stick support on BE800, BE900 and GE800
https://community.tp-link.com/en/home/forum/topic/711638
