### ISSUE TITLE
MEO Portugal / UFiber NanoG / Help Identifying my GPON SFP+ Module

### ISSUE THREAD

**Issue by dylangerdaly** [Anime4000/RTL960x#272]
Hello,

I'm attempting to replace my ISP's ONT with an SFP+ Module I got from Aliexpress

This is the listing: https://www.aliexpress.com/item/4000537015384.html

> E/GXPON SFP ONU Stick With MAC SC Connector DDM pon module 1490/1330nm 1.25/2.5G XPON/EPON/GPON(1.244Gbps/2.55G)802.3ah E/GXPON

I've been able to successfully replace it with a Ubquiti UFiber NanoG, only changing the Serial to match the original ONT works, however download is limited to ~250Mbps and upload is limited to 1Mbps, I assume this is because of a laser issue.

Ultimately I'd like to use the SFP+ Module above however I'm not sure what version of the modified firmware I should install, setting the GPON Serial Number results in O0 (WRONG) from the OLT.

Any help is greatly appreciated 

Screenshot of NanoG
![2024-03-27-094638](https://github.com/Anime4000/RTL960x/assets/7969682/cfe12de2-2233-41c9-8bed-5eed3369e786)

**Comment by Anime4000** [comment]
have you tried change `OMCI_TM_OPT` `0` `1` `2` (default) ?

**Comment by dylangerdaly** [comment]
MEO works with the SFP+
