### ISSUE TITLE
HSGQ SFP XPON ONU Stick firmware

### ISSUE THREAD

**Issue by qatar2030** [Anime4000/RTL960x#291]
Would someone please help me to find the latest firmware for HSGQ SFP XPON ONU Stick

**Comment by onion83** [comment]
Official | 220923：
https://github.com/Anime4000/RTL960x/tree/main/Firmware/DFP-34X-2C2

Lastest | 240408 : (via https://github.com/Anime4000/RTL960x/issues/271)
https://www.mediafire.com/file/98qt78yw02netme/M110_sfp_ODI_240408.tar/file
