### ISSUE TITLE
V2801F backup bug

### ISSUE THREAD

**Issue by komashchenko** [Anime4000/RTL960x#302]
When trying to backup configuration, the error "Invalid config file!" and the module goes into reboot
Tested on firmware 220425 and 240204
![backup bug](https://github.com/Anime4000/RTL960x/assets/22940384/9e05fd97-a66d-4b3c-b7f7-233d45f91ded)

**Comment by Anime4000** [comment]
I think this code cause the bug
![image](https://github.com/Anime4000/RTL960x/assets/1908715/e784c544-dad7-4897-a6c1-54993f1fd0ab)

I don't have V2801F to test, so, please try:
[V2801F_V1.9.0-240614_unpack_first.zip](https://github.com/user-attachments/files/15827047/V2801F_V1.9.0-240614_unpack_first.zip)

**Comment by komashchenko** [comment]
Thanks, it's working now
