### ISSUE TITLE
Thanks from Bangladesh 

### ISSUE THREAD

**Issue by jituboss** [Anime4000/RTL960x#307]
Successfully replaced my stock ONU with vsol v2801f sfp stick onu with Mikrotik routerboard.

ISP: Dot-Internet Dhaka
OLT Auth: Needed to reset Mac address by generating correct VS Auth Key.

Was stuck on O5 (Operation state) for couple of days to to figure out how to dial PPPoE properly from mikrotik.

Then could use the diag tool of the module to list l2 table addresses and found VLAN id of nearby AC router of ISP.

Great documentation!

**Comment by Anime4000** [comment]
Great! I am glad that works for you!
