### ISSUE TITLE
ODI DFP-34X-2C3 unusual received packets

### ISSUE THREAD

**Issue by rapdodge** [Anime4000/RTL960x#325]
Hello there, I'm new to using the XPON ONU SFP. I'm using a media converter and I've seen there is unusual packets that received by my router

![image](https://github.com/user-attachments/assets/f20e4e97-b228-43b2-86a9-c855ca79910b)

My ISP is using VLAN 406, and I don't know why the eth0 is having very much receive packets and the vlan 406 even still not reach half of it

Is there anyone have idea about that?

Best regards,

**Comment by rapdodge** [comment]
This is the `bmon -p eth0`

![image](https://github.com/user-attachments/assets/51512f58-8f62-42d8-8ded-be7a31fdf002)

This is the `iftop -i eth0`

![{B6E5EE89-DAC5-4BFC-9AE5-EABF3763A33D}](https://github.com/user-attachments/assets/09771d1c-2f8e-4133-afc6-7d9bb7ef30e3)

This is the `ip ro`

![image](https://github.com/user-attachments/assets/9c4afa3b-78ab-48d2-b3a8-d8ae3fb3a761)

**Comment by Anime4000** [comment]
this could be IPTV ?

**Comment by rapdodge** [comment]
> this could be IPTV ?

Maybe, but I didn't assign any VLAN to it...

![{84F5DF55-14D9-41AB-83D4-0FE57998DCD0}](https://github.com/user-attachments/assets/76c93305-33d1-431f-98dc-b95c97d269ad)

How to eliminate it?

**Comment by vuducdong** [comment]
> > this could be IPTV ?
> 
> 
> 
> Maybe, but I didn't assign any VLAN to it...
> 
> 
> 
> ![{84F5DF55-14D9-41AB-83D4-0FE57998DCD0}](https://github.com/user-attachments/assets/76c93305-33d1-431f-98dc-b95c97d269ad)
> 
> 
> 
> How to eliminate it?

Enable iGMP Snooping to block it.

Web sfp - LAN - IGMP Snooping (Enable)

**Comment by rapdodge** [comment]
> > > this could be IPTV ?
> > 
> > 
> > Maybe, but I didn't assign any VLAN to it...
> > ![{84F5DF55-14D9-41AB-83D4-0FE57998DCD0}](https://private-user-images.githubusercontent.com/33513626/378075479-76c93305-33d1-431f-98dc-b95c97d269ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzkzMDksIm5iZiI6MTcyOTMzOTAwOSwicGF0aCI6Ii8zMzUxMzYyNi8zNzgwNzU0NzktNzZjOTMzMDUtMzNkMS00MzFmLTk4ZGMtYjk1Yzk3ZDI2OWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDExNTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYTIzMTU5MWRkMmU5MWE3Zjg1NGMxN2NlNzQ4YWNiZDVmY2U0ZTg5MzI0ZGI2MWRlZTZmMjEyYTljOGE5ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wDrzXxIhiorIHltLUQcVmZTtTgOjZLQBfdkU_yM9VoA)
> > How to eliminate it?
> 
> Enable iGMP Snooping to block it.
> 
> Web sfp - LAN - IGMP Snooping (Enable)

Thanks, it's slowing down right now
