### ISSUE TITLE
Replacing HG8240H5 with DFP-34X-2C3 @ ER-X-SFP: no TX power 

### ISSUE THREAD

**Issue by snizovtsev** [Anime4000/RTL960x#335]
Hello, I'm trying to ditch my Huawei ONT with DFP-34X-2C3 (same as C2 but with green connector). It comes with V1.0-220923 factory firmware. My ISP is Mtel Montenegro (MTS Serbia branch).

My configuration looks like this:

![image](https://github.com/user-attachments/assets/bc676549-59b5-4a42-a002-ae845ed4ce18)

In addition, I've tried setting `OMCI_OLT_MODE` from 0 to 1.

I've generated MAC KEY using with your `VsAuthKeyGen.exe` using my new HW version and MAC. Unfortunately, I've lost my original MAC KEY because it seems backup xml does not contain it.

Unfortunately, the stick reports that there are no TX power at all and even won't try to authenticate the connection. RX power looks similar to what I get with Huawei:

![Screenshot 2024-11-10 at 00-13-24 BroadBand Device Webserver](https://github.com/user-attachments/assets/3526c91a-afb0-48f2-8f4c-940eb32ba3d2)
![Screenshot 2024-11-10 at 00-31-00 HG8240H5](https://github.com/user-attachments/assets/46f45665-e4df-498d-be07-201950168580)
![Screenshot 2024-11-10 at 00-31-28 HG8240H5](https://github.com/user-attachments/assets/2711b68e-2d6c-476b-bc2f-b2df6e65358b)

Could you help me with any suggestions related to this step?

Thank you in advance!

**Comment by vuducdong** [comment]
you change mac sfp to ec84b444d3e6

and mac key to 1245734692fb7026c656cfd5ceb382b2

And fill any for loid and loid pass

Ex: 

Loid = 12345678
Loid pass = 123456

**Comment by snizovtsev** [comment]
@vuducdong your MAC helped me, thank you very much! I got stable O5 state now:

![image](https://github.com/user-attachments/assets/ee7401e2-5f7c-4c1c-b650-4c1aaf308d91)

So, It seems problem relies in `VsAuthKeyGen.exe`. It outputs the following for your key pair:

```
$ wine VsAuthKeyGen.exe EC84B444D3E6 168D.A
7E6B5902B10A57E8C685880F1708BC23 
```

How do I generate my own unique MAC KEY then?

**Comment by snizovtsev** [comment]
I just figured out that `echo -n "hsgq1.9aEC84B444D3E6" | md5sum` algo from `providerforum.nl` matches `1245734692fb7026c656cfd5ceb382b2`. I will try to clone my original Huawei MAC in that way.

**Comment by Anime4000** [comment]
> I just figured out that `echo -n "hsgq1.9aEC84B444D3E6" | md5sum` algo from `providerforum.nl` matches `1245734692fb7026c656cfd5ceb382b2`. I will try to clone my original Huawei MAC in that way.

I have link the Keygen in the big menu:
![image](https://github.com/user-attachments/assets/3e2e578b-9180-486a-93a8-3ff34c7f6289)

second, GPON doesn't care mac address unless you on EPON network
