### ISSUE TITLE
DFP-34X-2C2 v210702 Vlan 10 – VoIP

### ISSUE THREAD

**Issue by Karetov** [Anime4000/RTL960x#47]
Hello.

With a successful connection, VLAN 10 is created, which I cannot edit. (Vlan 10 – VoIP)
I reset the ODI settings, disconnected from the network, then created my VLAN 10 connection, but after connecting, another VLAN 10 connection appeared next to it. 
On the tab with editing VLAN parameters, VLAN 10 created (apparently) by the provider is not displayed. 
Can I edit this connection somehow?

In other firmware versions, this connection is not displayed, but the LOIDstatus – WRONG connection is not established in them.

Also, after the reboot, multicast vlan id flies off, the provider's vlan10, which causes a conflict of IP addresses on the router side.

![Screenshot 2022-07-05 at 12 10 49](https://user-images.githubusercontent.com/45533720/177295187-32e66470-7ca9-457e-8d98-560d83f9efa4.png)

**Comment by Anime4000** [comment]
if got LOID Status Wrong or `O0`
high chance that your MAC_KEY is wrong

**Comment by Karetov** [comment]
The problem with Loidstatus on all firmware except 210702. The MAC address on the ODI is registered on the provider's terminal. The question is more about VLAN

**Comment by Anime4000** [comment]
This one I not really sure, 

the PON WAN, only one VLAN can be Port Mapping

when you add another PON WAN entry and tick Port Mapping, it will cause previous mapping unticked

I not sure that PON WAN is meant for PVID or something else...

Have you try not to tick Port Mapping and set VLAN at router side?

**Comment by Karetov** [comment]
Perhaps I don't quite understand you, I'm sorry. Initially, I had a question about the nas0_2 connection, which is added by itself, after a successful connection and the status 05. And I can't edit it in any way and even see it in the settings, only on the screen shown in the screenshot

**Comment by Karetov** [comment]
Everything worked out, it was in the vendor's parameters, as you said, thank you!

Is it possible to assign different vlan IDs on the SFP module. for VoIP and Internet?

**Comment by Karetov** [comment]
Hello
I tried to update the MAC_KEY after changing the MAC address, but I get this response. Please tell me what the problem may be

# flash set MAC_KEY 96a3c*****645
[ERR] Warning, unknown dir name: MAC_KEY
[ERR] Warning, unknown dir name: MAC_KEY
GET fail.

**Comment by Anime4000** [comment]
oh, which version are you using?

**Comment by Karetov** [comment]
v210702

**Comment by Karetov** [comment]
Figured it out
On this version, apparently, MAC_KEY is not used

**Comment by Karetov** [comment]
@Anime4000 Hello

I managed to start the internet on the hybrid firmware M114_sfp_ODI_hybrid_220527.tar, but apparently I need M114_sfp_ODI_220304.tar or M114_sfp_ODI_Vlan_220414.tar to start VoIP. The problem is that on these firmware I can't start the internet and the VLAN tab is displayed like this
![Uploading Screenshot 2022-07-21 at 22.12.56.png…]()

**Comment by Karetov** [comment]
@Anime4000 Hello

I managed to start the internet on the hybrid firmware M114_sfp_ODI_hybrid_220527.tar, but apparently I need M114_sfp_ODI_220304.tar or M114_sfp_ODI_Vlan_220414.tar to start VoIP. The problem is that on these firmware I can't start the internet and the VLAN tab is displayed like this
![Uploading Screenshot 2022-07-21 at 22.12.56.png…]()

**Comment by Anime4000** [comment]
@Karetov 
try `omcicli mib get 84` in telnet, past here the results

that command will show available VLAN

**Comment by Karetov** [comment]
![Uploading Screenshot 2022-07-21 at 22.25.39.png…]()

**Comment by Karetov** [comment]
<img width="1680" alt="Screenshot 2022-07-21 at 22 29 12" src="https://user-images.githubusercontent.com/45533720/180618278-ffd3fa72-294b-4363-bc80-3c3c2e327773.png">
<img width="1680" alt="Screenshot 2022-07-21 at 22 25 39" src="https://user-images.githubusercontent.com/45533720/180618283-b2b34c78-a645-4320-a365-1758671c3bd7.png">

**Comment by Anime4000** [comment]
try each VLAN 10,20,30,32,50,60

**Comment by Karetov** [comment]
I know for sure that the Internet is 30, telephony is 10, IPTV is 20.

I wonder why the interface is not fully displayed on the firmware for the VLAN

**Comment by Karetov** [comment]
The problem is solved, VoIP works on the firmware M114_sfp_ODI_220817.tar
