### ISSUE TITLE
[DFP-34X-2C2] Newest firmware not shown Rx Power

### ISSUE THREAD

**Issue by jang5th** [Anime4000/RTL960x#73]
Hi,

I have just upgraded [M114_sfp_ODI_220817.tar](https://github.com/Anime4000/RTL960x/blob/main/Firmware/DFP-34X-2C2/M114_sfp_ODI_220817.tar) but it have not shown Rx Power. How do I fix it?
![image](https://user-images.githubusercontent.com/7375995/189638048-c69d5dd0-b80e-4e0d-ad0d-c748b3b232f7.png)

**Comment by Anime4000** [comment]
that's odd, everyone works just fine,
have you try factory reset? erase mtd3 partition

**Comment by jang5th** [comment]
> that's odd, everyone works just fine, have you try factory reset? erase mtd3 partition

Yes, I did: flash_eraseall /dev/mtd3

Can you please help me how to transfer mtd from Ubuntu to ODI SFP via nc command?
