### ISSUE TITLE
Incompatibility between Mikrotik CSS610-8G-2S+IN and V2801F V-SOL

### ISSUE THREAD

**Issue by nazar-pc** [Anime4000/RTL960x#86]
Hi folks, when I insert module into running switch, switch doesn't seem to recognize it at all.
If I reboot switch with module inserted, it prints 0x03 character (ASCII) as vendor and doesn't recognize it as anything useful otherwise.

Does this mean switch lacks drivers or did anyone experience anything similar?

**Comment by Anime4000** [comment]
the switch is latest firmware?
have you tried Disable Auto Negotiate ?

**Comment by nazar-pc** [comment]
Switch was at latest firmware SwOS Lite 2.14.
Auto-negotiation was enabled, Mikrotik support also suggested to disable and fix to 1G and indeed, module seems to be recognized now, will look into how to get it to actually work now, thanks!

**Comment by nazar-pc** [comment]
If I can ask another question here: how do I get to web interface?
I have isolated SFP and one Ethernet into separate group, assigned 192.168.1.2 to the machine, but 192.192.1.1 is unreachable and SwOS doesn't see any MAC addresses on that interface either. Looks like there is another trick I'm missing.

**Comment by Anime4000** [comment]
I see, for now I put CSS610-8G-2S+IN in incompatible list

**Comment by nazar-pc** [comment]
I think in the end the issue is not the switch, it is OLT frm Raisecom that rejects non-Raisecom ONU and because of this ONU's Web UI doesn't even start.

**Comment by Anime4000** [comment]
that troublesome, with extended OMCI check can't make PON Stick to work

**Comment by nazar-pc** [comment]
Finally had success with another ONU stick on CSS610-8G-2S+IN, so the switch as such seems to be fine
