### ISSUE TITLE
UF-Instant WEB interface crashes when attempting to login

### ISSUE THREAD

**Issue by FiberExplorer** [Anime4000/RTL960x#96]
I have modded the UF-Instant firmware "4.3.1 or 4.4.2 doesn't change the outcome" but when I try log in the WebGui 
crash and tell connection refused and no pages are available.

Could someone give me some tips?

Many Thanks!

**Comment by Anime4000** [comment]
is that has been flashed with V2801F ?

**Comment by FiberExplorer** [comment]
> is that has been flashed with V2801F ?

I have flashed with this procedure and relative firmware suggested in the guide at https://github.com/stich86/UF-Instant-Mod.
if I need to reflash please so kindly to suggest the appropriate firmware and a procedure.

Manty Thanks

**Comment by Anime4000** [comment]
for fast reply and easy help, join this discord: https://discord.gg/KUHwDgkRtR

**Comment by FiberExplorer** [comment]
I've joined and I'll try to find a possible solution before post any request.   

Many Thanks!!
